# Retail Intelligence and Consumer Analytics

## Data Loading Phase

### Analytics Week 2 Internship Project

Dataset Size : 100,000+ Records

Objective:
Load and inspect retail sales dataset before preprocessing.

# Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns',None)

# Read Dataset

In [2]:
retail_df=pd.read_csv('../data/raw/store_sales_data (2).csv')

In [3]:
retail_df.head()

,Customer ID,Customer Name,Last Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,Country,Segment,Sales Date,Order ID,Order Date,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
0,CUST000001,Curtis,Krause,1973-11-29,3344.69,2023,Large,Tier 1,Fast Food,East,India,Consumer,2023-03-11,ORD000001,2020-04-13,2020-04-18,Same Day,West Bengal,700001,PROD000001,Burgers,Burgers - 718,3,0.09,448.24
1,CUST000002,Jeremy,Foster,1987-08-30,37094.41,2022,Medium,Tier 2,Fast Food,East,India,Corporate,2023-09-09,ORD000002,2021-01-08,2021-01-11,Standard Class,Punjab,160001,PROD000002,Pizzas,Pizzas - 519,5,0.39,3134.34
2,CUST000003,Ariel,Mccann,1980-12-15,35501.08,2023,Large,Village,Electric Appliances,South,India,Consumer,2022-08-15,ORD000003,2020-08-11,2020-08-16,Second Class,Gujarat,380001,PROD000003,Fans,Fans - 395,6,0.07,8324.21
3,CUST000004,Colleen,Maynard,1989-05-23,8969.33,2021,Medium,Village,Dairy Products,East,India,Corporate,2021-01-23,ORD000004,2021-10-10,2021-10-16,First Class,West Bengal,700001,PROD000004,Milk,Milk - 798,4,0.18,1962.66
4,CUST000005,Gina,Holden,1957-12-31,35530.44,2021,Small,Village,Sessional Fruits & Vegetables,West,India,Consumer,2020-12-24,ORD000005,2019-01-22,2019-01-25,Standard Class,Delhi,110001,PROD000005,Tomatoes,Tomatoes - 442,4,0.27,2843.93

In [4]:
retail_df.tail()

,Customer ID,Customer Name,Last Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,Country,Segment,Sales Date,Order ID,Order Date,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
99995,CUST099996,Thomas,Adams,2018-02-02,254.35,2020,Large,Tier 1,Furniture,East,India,Corporate,2019-08-05,ORD099996,2019-01-31,2019-02-05,First Class,Gujarat,380001,PROD099996,Beds,Beds - 169,2,0.12,61.84
99996,CUST099997,Clifford,Dillon,1955-08-11,846.66,2019,Medium,Tier 2,Sessional Fruits & Vegetables,North,India,Corporate,2019-01-24,ORD099997,2020-04-02,2020-04-09,Same Day,Rajasthan,302001,PROD099997,Tomatoes,Tomatoes - 291,1,0.43,118.60
99997,CUST099998,Kelly,Deleon,1991-02-27,12165.34,2019,Large,Tier 2,Furniture,East,India,Consumer,2019-03-10,ORD099998,2021-06-27,2021-07-02,Standard Class,Maharashtra,400001,PROD099998,Chairs,Chairs - 381,4,0.13,2100.20
99998,CUST099999,Katie,Moses,1990-10-21,41242.99,2019,Small,Tier 1,Fast Food,North,India,Consumer,2023-11-29,ORD099999,2019-07-27,2019-08-01,Second Class,Karnataka,560001,PROD099999,Sandwiches,Sandwiches - 961,4,0.41,4674.57
99999,CUST100000,Jeremy,Combs,2016-12-27,47402.45,2019,Medium,Village,Fast Food,North,India,Corporate,2020-07-02,ORD100000,2020-02-20,2020-02-24,Same Day,Maharashtra,400001,PROD100000,Burgers,Burgers - 611,5,0.32,8490.54

In [5]:
retail_df.shape

(100000, 25)

In [6]:
retail_df.columns

Index(['Customer ID', 'Customer Name', 'Last Name', 'Date of Birth', 'Sales',
       'Year', 'Outlet Type', 'City Type', 'Category of Goods', 'Region',
       'Country', 'Segment', 'Sales Date', 'Order ID', 'Order Date',
       'Ship Date', 'Ship Mode', 'State', 'Postal Code', 'Product ID',
       'Sub-Category', 'Product Name', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [7]:
retail_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Customer ID        100000 non-null  object
 1   Customer Name      100000 non-null  object
 2   Last Name          100000 non-null  object
 3   Date of Birth      100000 non-null  object
 4   Sales              100000 non-null  float64
 5   Year               100000 non-null  int64
 6   Outlet Type        100000 non-null  object
 7   City Type          100000 non-null  object
 8   Category of Goods  100000 non-null  object
 9   Region             100000 non-null  object
 10  Country            100000 non-null  object
 11  Segment            100000 non-null  object
 12  Sales Date         100000 non-null  object
 13  Order ID           100000 non-null  object
 14  Order Date         100000 non-null  object
 15  Ship Date          100000 non-null  object
 16  Ship Mode          100000 non-null  object
 17  State              100000 non-null  object
 18  Postal Code        100000 non-null  int64
 19  Product ID         100000 non-null  object
 20  Sub-Category       100000 non-null  object
 21  Product Name       100000 non-null  object
 22  Quantity           100000 non-null  int64
 23  Discount           100000 non-null  float64
 24  Profit             100000 non-null  float64
dtypes: float64(3), int64(3), object(19)
memory usage: 19.1+ MB

In [8]:
retail_df.describe()

,Sales,Year,Postal Code,Quantity,Discount,Profit
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,25084.410142,2020.999910,388985.180000,5.493760,0.251320,3755.305114
std,14403.187686,1.413757,184192.704685,2.876102,0.144324,2639.852035
min,100.570000,2019.000000,110001.000000,1.000000,0.000000,6.520000
25%,12618.030000,2020.000000,226001.000000,3.000000,0.130000,1651.105000
50%,25134.695000,2021.000000,380001.000000,5.000000,0.250000,3317.450000
75%,37575.850000,2022.000000,560001.000000,8.000000,0.380000,5363.845000
max,49999.890000,2023.000000,700001.000000,10.000000,0.500000,14563.670000

In [9]:
retail_df.sample(5)

,Customer ID,Customer Name,Last Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,Country,Segment,Sales Date,Order ID,Order Date,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
89012,CUST089013,Calvin,Cole,1981-02-01,2850.49,2022,Small,Tier 2,Electric Appliances,South,India,Consumer,2022-07-26,ORD089013,2022-10-18,2022-10-19,First Class,West Bengal,700001,PROD089013,Washing Machines,Washing Machines - 485,2,0.01,359.11
53192,CUST053193,Nancy,Weber,1977-12-12,28916.82,2023,Medium,Tier 2,Electric Appliances,East,India,Consumer,2021-02-12,ORD053193,2020-10-08,2020-10-13,Same Day,Uttar Pradesh,226001,PROD053193,Microwaves,Microwaves - 699,2,0.29,5587.08
21004,CUST021005,Sean,Moore,1989-02-18,42784.41,2023,Small,Tier 2,Electric Appliances,East,India,Corporate,2019-11-06,ORD021005,2021-03-22,2021-03-25,First Class,Maharashtra,400001,PROD021005,Microwaves,Microwaves - 531,7,0.12,8346.69
60037,CUST060038,Joshua,Hogan,2013-06-12,3994.78,2020,Small,Tier 2,Sessional Fruits & Vegetables,South,India,Corporate,2021-04-09,ORD060038,2020-05-09,2020-05-10,Second Class,Rajasthan,302001,PROD060038,Carrots,Carrots - 600,1,0.24,743.39
47254,CUST047255,Stephanie,Griffin,1975-05-09,13620.46,2021,Small,Tier 2,Sessional Fruits & Vegetables,East,India,Corporate,2020-12-13,ORD047255,2022-01-13,2022-01-20,Same Day,Rajasthan,302001,PROD047255,Mangoes,Mangoes - 221,8,0.21,2185.68