# Data Quality Assessment & Preparation

In [1]:
import pandas as pd

In [2]:
retail_df=pd.read_csv('../data/raw/store_sales_data (2).csv')

In [3]:
retail_df.isnull().sum()

Customer ID          0
Customer Name        0
Last Name            0
Date of Birth        0
Sales                0
Year                 0
Outlet Type          0
City Type            0
Category of Goods    0
Region               0
Country              0
Segment              0
Sales Date           0
Order ID             0
Order Date           0
Ship Date            0
Ship Mode            0
State                0
Postal Code          0
Product ID           0
Sub-Category         0
Product Name         0
Quantity             0
Discount             0
Profit               0
dtype: int64

In [4]:
retail_df.duplicated().sum()

np.int64(0)

In [5]:
retail_df.nunique()

Customer ID          100000
Customer Name           690
Last Name              1000
Date of Birth         24536
Sales                 98976
Year                      5
Outlet Type               3
City Type                 3
Category of Goods         6
Region                    4
Country                   1
Segment                   2
Sales Date             1826
Order ID             100000
Order Date             1826
Ship Date              1832
Ship Mode                 4
State                    10
Postal Code              10
Product ID           100000
Sub-Category             24
Product Name          21365
Quantity                 10
Discount                 51
Profit                94247
dtype: int64

# Convert Datatypes

In [6]:
date_cols=[

'Order Date',
'Ship Date',
'Sales Date',
'Date of Birth'

]

In [7]:
for col in date_cols:

    retail_df[col]=pd.to_datetime(retail_df[col])

In [8]:
retail_df.dtypes

Customer ID                  object
Customer Name                object
Last Name                    object
Date of Birth        datetime64[ns]
Sales                       float64
Year                          int64
Outlet Type                  object
City Type                    object
Category of Goods            object
Region                       object
Country                      object
Segment                      object
Sales Date           datetime64[ns]
Order ID                     object
Order Date           datetime64[ns]
Ship Date            datetime64[ns]
Ship Mode                    object
State                        object
Postal Code                   int64
Product ID                   object
Sub-Category                 object
Product Name                 object
Quantity                      int64
Discount                    float64
Profit                      float64
dtype: object

In [9]:
retail_df.describe(include='all')

,Customer ID,Customer Name,Last Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,...,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
count,100000,100000,100000,100000,100000.000000,100000.000000,100000,100000,100000,100000,...,100000,100000,100000,100000.000000,100000,100000,100000,100000.000000,100000.000000,100000.000000
unique,100000,690,1000,NaN,NaN,NaN,3,3,6,4,...,NaN,4,10,NaN,100000,24,21365,NaN,NaN,NaN
top,CUST099984,Michael,Smith,NaN,NaN,NaN,Medium,Tier 1,Household Items,East,...,NaN,First Class,Rajasthan,NaN,PROD099984,Mops,Beds - 684,NaN,NaN,NaN
freq,1,2345,2156,NaN,NaN,NaN,33512,33671,16790,25117,...,NaN,25078,10240,NaN,1,4397,15,NaN,NaN,NaN
mean,NaN,NaN,NaN,1984-03-06 03:10:31.584000128,25084.410142,2020.999910,NaN,NaN,NaN,NaN,...,2021-07-05 14:08:51.072000256,NaN,NaN,388985.180000,NaN,NaN,NaN,5.493760,0.251320,3755.305114
min,NaN,NaN,NaN,1950-01-01 00:00:00,100.570000,2019.000000,NaN,NaN,NaN,NaN,...,2019-01-02 00:00:00,NaN,NaN,110001.000000,NaN,NaN,NaN,1.000000,0.000000,6.520000
25%,NaN,NaN,NaN,1966-12-13 12:00:00,12618.030000,2020.000000,NaN,NaN,NaN,NaN,...,2020-04-04 00:00:00,NaN,NaN,226001.000000,NaN,NaN,NaN,3.000000,0.130000,1651.105000
50%,NaN,NaN,NaN,1984-02-26 00:00:00,25134.695000,2021.000000,NaN,NaN,NaN,NaN,...,2021-07-06 00:00:00,NaN,NaN,380001.000000,NaN,NaN,NaN,5.000000,0.250000,3317.450000
75%,NaN,NaN,NaN,2001-05-12 00:00:00,37575.850000,2022.000000,NaN,NaN,NaN,NaN,...,2022-10-05 00:00:00,NaN,NaN,560001.000000,NaN,NaN,NaN,8.000000,0.380000,5363.845000
max,NaN,NaN,NaN,2018-06-13 00:00:00,49999.890000,2023.000000,NaN,NaN,NaN,NaN,...,2024-01-07 00:00:00,NaN,NaN,700001.000000,NaN,NaN,NaN,10.000000,0.500000,14563.670000
std,NaN,NaN,NaN,NaN,14403.187686,1.413757,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,184192.704685,NaN,NaN,NaN,2.876102,0.144324,2639.852035

In [10]:
retail_df.memory_usage()

Index                   132
Customer ID          800000
Customer Name        800000
Last Name            800000
Date of Birth        800000
Sales                800000
Year                 800000
Outlet Type          800000
City Type            800000
Category of Goods    800000
Region               800000
Country              800000
Segment              800000
Sales Date           800000
Order ID             800000
Order Date           800000
Ship Date            800000
Ship Mode            800000
State                800000
Postal Code          800000
Product ID           800000
Sub-Category         800000
Product Name         800000
Quantity             800000
Discount             800000
Profit               800000
dtype: int64

In [11]:
retail_df.memory_usage().sum()/1024**2

np.float64(19.073612213134766)

In [12]:
retail_df.head()

,Customer ID,Customer Name,Last Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,...,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
0,CUST000001,Curtis,Krause,1973-11-29,3344.69,2023,Large,Tier 1,Fast Food,East,...,2020-04-18,Same Day,West Bengal,700001,PROD000001,Burgers,Burgers - 718,3,0.09,448.24
1,CUST000002,Jeremy,Foster,1987-08-30,37094.41,2022,Medium,Tier 2,Fast Food,East,...,2021-01-11,Standard Class,Punjab,160001,PROD000002,Pizzas,Pizzas - 519,5,0.39,3134.34
2,CUST000003,Ariel,Mccann,1980-12-15,35501.08,2023,Large,Village,Electric Appliances,South,...,2020-08-16,Second Class,Gujarat,380001,PROD000003,Fans,Fans - 395,6,0.07,8324.21
3,CUST000004,Colleen,Maynard,1989-05-23,8969.33,2021,Medium,Village,Dairy Products,East,...,2021-10-16,First Class,West Bengal,700001,PROD000004,Milk,Milk - 798,4,0.18,1962.66
4,CUST000005,Gina,Holden,1957-12-31,35530.44,2021,Small,Village,Sessional Fruits & Vegetables,West,...,2019-01-25,Standard Class,Delhi,110001,PROD000005,Tomatoes,Tomatoes - 442,4,0.27,2843.93

In [13]:
retail_df.to_csv(

'../data/processed/retail_cleaned.csv',

index=False
)