# Business Feature Construction

In [2]:
import pandas as pd

retail_df=pd.read_csv('../data/processed/retail_cleaned.csv')

In [3]:
retail_df['Order Date']=pd.to_datetime(retail_df['Order Date'])

In [4]:
retail_df['Ship Date']=pd.to_datetime(retail_df['Ship Date'])

In [5]:
retail_df['Date of Birth']=pd.to_datetime(retail_df['Date of Birth'])

In [6]:
retail_df['Month']=retail_df['Order Date'].dt.month_name()

In [7]:
retail_df['Year']=retail_df['Order Date'].dt.year

In [8]:
retail_df['Quarter']=retail_df['Order Date'].dt.quarter

In [9]:
retail_df['Weekday']=retail_df['Order Date'].dt.day_name()

In [10]:
retail_df['Age']=2026-retail_df['Date of Birth'].dt.year

In [11]:
retail_df['Delivery Days']=(
retail_df['Ship Date']
-
retail_df['Order Date']
).dt.days

In [12]:
retail_df['Profit Margin']=(
retail_df['Profit']/retail_df['Sales']
)*100

KeyError: 'Sales'

In [ ]:
retail_df[['Age','Profit Margin']].head()

   Age  Profit Margin
0   53      13.401541
1   39       8.449629
2   46      23.447766
3   37      21.881902
4   69       8.004207

In [ ]:
retail_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 31 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Customer ID        100000 non-null  object
 1   Customer Name      100000 non-null  object
 2   Last Name          100000 non-null  object
 3   Date of Birth      100000 non-null  datetime64[ns]
 4   Sales              100000 non-null  float64
 5   Year               100000 non-null  int32
 6   Outlet Type        100000 non-null  object
 7   City Type          100000 non-null  object
 8   Category of Goods  100000 non-null  object
 9   Region             100000 non-null  object
 10  Country            100000 non-null  object
 11  Segment            100000 non-null  object
 12  Sales Date         100000 non-null  object
 13  Order ID           100000 non-null  object
 14  Order Date         100000 non-null  datetime64[ns]
 15  Ship Date          100000 non-null  datetime64[ns]
 16  Ship Mode          100000 non-null  object
 17  State              100000 non-null  object
 18  Postal Code        100000 non-null  int64
 19  Product ID         100000 non-null  object
 20  Sub-Category       100000 non-null  object
 21  Product Name       100000 non-null  object
 22  Quantity           100000 non-null  int64
 23  Discount           100000 non-null  float64
 24  Profit             100000 non-null  float64
 25  Month              100000 non-null  object
 26  Quarter            100000 non-null  int32
 27  Weekday            100000 non-null  object
 28  Age                100000 non-null  int32
 29  Delivery Days      100000 non-null  int64
 30  Profit Margin      100000 non-null  float64
dtypes: datetime64[ns](3), float64(4), int32(3), int64(3), object(18)
memory usage: 22.5+ MB

In [13]:
retail_df.head()

,Customer ID,Customer Name,Last Name,Date of Birth,Sales_x,Year,Outlet Type,City Type,Category of Goods,Region,...,Discount,Profit,Month,Quarter,Weekday,Age,Delivery Days,Profit Margin,Sales_y,Customer Segment
0,CUST000001,Curtis,Krause,1973-11-29,3344.69,2020,Large,Tier 1,Fast Food,East,...,0.09,448.24,April,2,Monday,53,5,13.401541,3344.69,Low Value
1,CUST000002,Jeremy,Foster,1987-08-30,37094.41,2021,Medium,Tier 2,Fast Food,East,...,0.39,3134.34,January,1,Friday,39,3,8.449629,37094.41,Medium Value
2,CUST000003,Ariel,Mccann,1980-12-15,35501.08,2020,Large,Village,Electric Appliances,South,...,0.07,8324.21,August,3,Tuesday,46,5,23.447766,35501.08,Medium Value
3,CUST000004,Colleen,Maynard,1989-05-23,8969.33,2021,Medium,Village,Dairy Products,East,...,0.18,1962.66,October,4,Sunday,37,6,21.881902,8969.33,Low Value
4,CUST000005,Gina,Holden,1957-12-31,35530.44,2019,Small,Village,Sessional Fruits & Vegetables,West,...,0.27,2843.93,January,1,Tuesday,69,3,8.004207,35530.44,Medium Value

In [14]:
retail_df.to_csv(

'../data/processed/retail_cleaned.csv',

index=False
)